addition in core and typings
AkaruiDevelopment/aoi.js-next pull request #2
Opened 2021-12-27 19:52 UTC by USERSATOSHI

# Core
```diff
+CommandManager
+Command
```
# Typings
```diff
+type CommandData
+type CommandName
+type CommandProperties
+interface CommandData
```
# Handlers
> ***Removed Try and Catch and uses .catch in AoiWarning.ts

2021-12-28 08:55 UTC, Rubenennj requested changes

2021-12-28 08:55 UTC, Rubenennj commented on src/typings/types/CommandTypes.ts
> +export type CommandProperties = "name" | "type" | "code" | string;
This type is not needed

2021-12-28 08:55 UTC, Rubenennj commented on src/typings/interfaces/CommandData.ts
> +	[CommandProperty: string]: any;
```suggestion
	[CommandProperty: string]: unknown;
```

2021-12-28 08:55 UTC, Rubenennj commented on src/core/Command.ts
> +}
The loop is unnecessary, this can be minified to
```suggestion
import { CommandData } from "../typings/interfaces/CommandData";
import {
	CommandName,
	CommandTypes
} from "../typings/types/CommandTypes";

export default class Command {
	data: CommandData;

	constructor(data: CommandData) {
		this.data = data
	}
}
```

2021-12-28 08:55 UTC, Rubenennj commented on src/handlers/AoiWarning.ts
> +		.catch((_) => undefined); //This will change when the package is published.
Import noop and use it in .catch

2021-12-28 09:55 UTC, USERSATOSHI commented on src/typings/types/CommandTypes.ts
> +export type CommandProperties = "name" | "type" | "code" | string;
hmm ok i will remove all

2021-12-28 09:57 UTC, USERSATOSHI commented on src/typings/types/CommandTypes.ts
> +export type CommandProperties = "name" | "type" | "code" | string;
one thing , i think we should keep CommandTypes cause rn its default but later we need to all more types
aka

CommandTypes = "default" |  "loop" | ....

2021-12-28 09:58 UTC, USERSATOSHI commented on src/core/Command.ts
> +}
done

2021-12-28 10:00 UTC, USERSATOSHI commented on src/handlers/AoiWarning.ts
> +		.catch((_) => undefined); //This will change when the package is published.
done

2021-12-28 10:00 UTC, USERSATOSHI commented on src/typings/types/CommandTypes.ts
> +export type CommandProperties = "name" | "type" | "code" | string;
done

2021-12-30 18:23 UTC, Leref requested changes

2021-12-30 18:23 UTC, Leref commented on src/structures/CommandManager.ts
> +export default class CommandManager {
This should have been kept AoiCommandManager.

2022-01-08 17:10 UTC, Rubenennj commented
closing this as this seems to never be edited + there are conflicts

2022-01-08 17:10 UTC, closed without merging